/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface MenuNav {}
  interface MenuTabs {}
  interface ScreenAbout {}
  interface ScreenNews {}
  interface ScreenProjects {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMenuNavElement extends Components.MenuNav, HTMLStencilElement {}
  var HTMLMenuNavElement: {
    prototype: HTMLMenuNavElement;
    new (): HTMLMenuNavElement;
  };

  interface HTMLMenuTabsElement extends Components.MenuTabs, HTMLStencilElement {}
  var HTMLMenuTabsElement: {
    prototype: HTMLMenuTabsElement;
    new (): HTMLMenuTabsElement;
  };

  interface HTMLScreenAboutElement extends Components.ScreenAbout, HTMLStencilElement {}
  var HTMLScreenAboutElement: {
    prototype: HTMLScreenAboutElement;
    new (): HTMLScreenAboutElement;
  };

  interface HTMLScreenNewsElement extends Components.ScreenNews, HTMLStencilElement {}
  var HTMLScreenNewsElement: {
    prototype: HTMLScreenNewsElement;
    new (): HTMLScreenNewsElement;
  };

  interface HTMLScreenProjectsElement extends Components.ScreenProjects, HTMLStencilElement {}
  var HTMLScreenProjectsElement: {
    prototype: HTMLScreenProjectsElement;
    new (): HTMLScreenProjectsElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'menu-nav': HTMLMenuNavElement;
    'menu-tabs': HTMLMenuTabsElement;
    'screen-about': HTMLScreenAboutElement;
    'screen-news': HTMLScreenNewsElement;
    'screen-projects': HTMLScreenProjectsElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface MenuNav {}
  interface MenuTabs {}
  interface ScreenAbout {}
  interface ScreenNews {}
  interface ScreenProjects {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'menu-nav': MenuNav;
    'menu-tabs': MenuTabs;
    'screen-about': ScreenAbout;
    'screen-news': ScreenNews;
    'screen-projects': ScreenProjects;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'menu-nav': LocalJSX.MenuNav & JSXBase.HTMLAttributes<HTMLMenuNavElement>;
      'menu-tabs': LocalJSX.MenuTabs & JSXBase.HTMLAttributes<HTMLMenuTabsElement>;
      'screen-about': LocalJSX.ScreenAbout & JSXBase.HTMLAttributes<HTMLScreenAboutElement>;
      'screen-news': LocalJSX.ScreenNews & JSXBase.HTMLAttributes<HTMLScreenNewsElement>;
      'screen-projects': LocalJSX.ScreenProjects & JSXBase.HTMLAttributes<HTMLScreenProjectsElement>;
    }
  }
}


