/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface MenuTabs {}
  interface ScreenAbout {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMenuTabsElement extends Components.MenuTabs, HTMLStencilElement {}
  var HTMLMenuTabsElement: {
    prototype: HTMLMenuTabsElement;
    new (): HTMLMenuTabsElement;
  };

  interface HTMLScreenAboutElement extends Components.ScreenAbout, HTMLStencilElement {}
  var HTMLScreenAboutElement: {
    prototype: HTMLScreenAboutElement;
    new (): HTMLScreenAboutElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'menu-tabs': HTMLMenuTabsElement;
    'screen-about': HTMLScreenAboutElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface MenuTabs extends JSXBase.HTMLAttributes<HTMLMenuTabsElement> {}
  interface ScreenAbout extends JSXBase.HTMLAttributes<HTMLScreenAboutElement> {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'menu-tabs': MenuTabs;
    'screen-about': ScreenAbout;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


